kind: Service
apiVersion: v1
metadata:
  name: game-server
spec:
  type: LoadBalancer
  loadBalancerIP: "34.170.12.255" # Insérez l'IP ici
  selector:
    app: game-server
  ports:
    - protocol: UDP
      port: 4712
      targetPort: 4712
