# Build stage
# Use node:22-slim to get a newer Node.js version
FROM node:22-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build || cat /root/.npm/_logs/*-debug-0.log

# Production stage (using Nginx to serve static files)
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 5173
CMD ["nginx", "-g", "daemon"]